FROM node:12.22-alpine AS builder

EXPOSE 3000/tcp
ENV TZ="Asia/Shanghai"

WORKDIR /srcdir
COPY . .

RUN yarn && \
    cd linux.dgut.edu.cn && \
    yarn build && \
    yarn cache clean && \
    cp -r blog/ build/


FROM alpine:3.12

ENV TZ="Asia/Shanghai"
RUN apk add --no-cache nodejs

WORKDIR /srv
COPY --from=builder /srcdir/linux.dgut.edu.cn/build/. .

CMD ["node", "index.mjs"]
